"""initial

Revision ID: 30d02806579f
Revises: 
Create Date: 2026-07-20 12:34:36.501694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d02806579f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('category', sa.Enum('INVENTORY', 'FORECAST', 'REORDER', 'EXCESS_STOCK', 'TRANSFER', 'SYSTEM', name='alertcategory'), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_audit_logs_created_at'), 'auth_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_email'), 'auth_audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_event_type'), 'auth_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_id'), 'auth_audit_logs', ['id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('API', 'DATABASE', 'CLOUD_STORAGE', 'LOCAL_FOLDER', name='datasourcetype'), nullable=False),
    sa.Column('provider', sa.Enum('SAP', 'MYSQL', 'POSTGRES', 'SQLITE', 'S3', 'MINIO', 'SUPPLIER', 'SALES', 'INVENTORY', 'WEATHER', 'CUSTOM', name='datasourceprovider'), nullable=True),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('connection_string', sa.String(length=1024), nullable=True),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('bucket_name', sa.String(length=255), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('sync_frequency', sa.String(length=50), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('record_count', sa.BigInteger(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('last_sync_duration', sa.Float(), nullable=True),
    sa.Column('next_sync', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_datasource_created_at', 'data_sources', ['created_at'], unique=False)
    op.create_index('idx_datasource_health', 'data_sources', ['health'], unique=False)
    op.create_index('idx_datasource_health_score', 'data_sources', ['health_score'], unique=False)
    op.create_index('idx_datasource_status', 'data_sources', ['status'], unique=False)
    op.create_index('idx_datasource_sync_frequency', 'data_sources', ['sync_frequency'], unique=False)
    op.create_index('idx_datasource_type', 'data_sources', ['type'], unique=False)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('excess_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('forecasted_demand_30days', sa.Float(), nullable=False),
    sa.Column('excess_quantity', sa.Float(), nullable=False),
    sa.Column('days_inventory_on_hand', sa.Float(), nullable=False),
    sa.Column('excess_level', sa.String(length=50), nullable=False),
    sa.Column('carrying_cost_per_unit_yearly', sa.Float(), nullable=False),
    sa.Column('total_carrying_cost', sa.Float(), nullable=False),
    sa.Column('action_recommended', sa.String(length=100), nullable=False),
    sa.Column('estimated_liquidation_value', sa.Float(), nullable=False),
    sa.Column('potential_savings', sa.Float(), nullable=False),
    sa.Column('storage_risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excess_stock_id'), 'excess_stock', ['id'], unique=False)
    op.create_index(op.f('ix_excess_stock_sku'), 'excess_stock', ['sku'], unique=False)
    op.create_index(op.f('ix_excess_stock_warehouse'), 'excess_stock', ['warehouse'], unique=False)
    op.create_table('inventory_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('holding_cost_per_year', sa.Float(), nullable=False),
    sa.Column('order_cost', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_skus_id'), 'inventory_skus', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_skus_sku'), 'inventory_skus', ['sku'], unique=True)
    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('from_warehouse', sa.String(length=100), nullable=False),
    sa.Column('to_warehouse', sa.String(length=100), nullable=False),
    sa.Column('transfer_quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('transfer_cost', sa.Float(), nullable=False),
    sa.Column('potential_cost_savings', sa.Float(), nullable=False),
    sa.Column('roi_percentage', sa.Float(), nullable=False),
    sa.Column('recommended_transfer_date', sa.DateTime(), nullable=False),
    sa.Column('expected_days_in_transit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfers_id'), 'inventory_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_sku'), 'inventory_transfers', ['sku'], unique=False)
    op.create_table('otp_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_id'), 'otp_records', ['id'], unique=False)
    op.create_index(op.f('ix_otp_records_user_email'), 'otp_records', ['user_email'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('suggested_action', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_sku'), 'recommendations', ['sku'], unique=False)
    op.create_table('reorder_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point_value', sa.Float(), nullable=False),
    sa.Column('economic_order_quantity', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('reorder_status', sa.String(length=100), nullable=False),
    sa.Column('days_until_stockout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reorder_points_id'), 'reorder_points', ['id'], unique=False)
    op.create_index(op.f('ix_reorder_points_sku'), 'reorder_points', ['sku'], unique=False)
    op.create_index(op.f('ix_reorder_points_warehouse'), 'reorder_points', ['warehouse'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('safety_stock_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('service_level', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('demand_std_dev', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('calculated_safety_stock', sa.Float(), nullable=False),
    sa.Column('current_safety_stock', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_stock_calculations_id'), 'safety_stock_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_sku'), 'safety_stock_calculations', ['sku'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_warehouse'), 'safety_stock_calculations', ['warehouse'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('scheduler_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduler_history_job', 'scheduler_history', ['job_id'], unique=False)
    op.create_index('idx_scheduler_history_started', 'scheduler_history', ['started_at'], unique=False)
    op.create_index('idx_scheduler_history_status', 'scheduler_history', ['status'], unique=False)
    op.create_index('idx_scheduler_history_type', 'scheduler_history', ['job_type'], unique=False)
    op.create_index(op.f('ix_scheduler_history_id'), 'scheduler_history', ['id'], unique=False)
    op.create_table('warehouse_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('economic_order_quantity', sa.Float(), nullable=True),
    sa.Column('last_reorder_date', sa.DateTime(), nullable=True),
    sa.Column('last_reorder_quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_inventory_id'), 'warehouse_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_inventory_sku'), 'warehouse_inventory', ['sku'], unique=False)
    op.create_index(op.f('ix_warehouse_inventory_warehouse'), 'warehouse_inventory', ['warehouse'], unique=False)
    op.create_table('connection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connection_history_datasource', 'connection_history', ['datasource_id'], unique=False)
    op.create_index('idx_connection_history_started_at', 'connection_history', ['started_at'], unique=False)
    op.create_index('idx_connection_history_status', 'connection_history', ['status'], unique=False)
    op.create_index(op.f('ix_connection_history_id'), 'connection_history', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='syncjobstatus'), nullable=True),
    sa.Column('current_step', sa.Enum('CONNECTING', 'DOWNLOADING', 'VALIDATING', 'SAVING', 'COMPLETED', name='syncjobstep'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('eta_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_jobs_created_at', 'sync_jobs', ['created_at'], unique=False)
    op.create_index('idx_sync_jobs_datasource', 'sync_jobs', ['datasource_id'], unique=False)
    op.create_index('idx_sync_jobs_status', 'sync_jobs', ['status'], unique=False)
    op.create_index('idx_sync_jobs_triggered_by', 'sync_jobs', ['triggered_by'], unique=False)
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_job_id'), 'sync_jobs', ['job_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('initial_password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('last_trained', sa.DateTime(), nullable=True),
    sa.Column('training_dataset', sa.String(length=255), nullable=True),
    sa.Column('training_size', sa.Integer(), nullable=True),
    sa.Column('best_accuracy', sa.Float(), nullable=True),
    sa.Column('best_rmse', sa.Float(), nullable=True),
    sa.Column('best_mae', sa.Float(), nullable=True),
    sa.Column('best_mape', sa.Float(), nullable=True),
    sa.Column('best_r2', sa.Float(), nullable=True),
    sa.Column('best_loss', sa.Float(), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('feature_set', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('artifact_size', sa.Integer(), nullable=True),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('framework_version', sa.String(length=50), nullable=True),
    sa.Column('python_version', sa.String(length=50), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('deployment_status', sa.String(length=50), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('production_version', sa.String(length=50), nullable=True),
    sa.Column('production_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_registry_best_accuracy', 'model_registry', ['best_accuracy'], unique=False)
    op.create_index('idx_model_registry_deployment_status', 'model_registry', ['deployment_status'], unique=False)
    op.create_index('idx_model_registry_is_active', 'model_registry', ['is_active'], unique=False)
    op.create_index('idx_model_registry_is_default', 'model_registry', ['is_default'], unique=False)
    op.create_index('idx_model_registry_is_favorite', 'model_registry', ['is_favorite'], unique=False)
    op.create_index('idx_model_registry_model_type', 'model_registry', ['model_type'], unique=False)
    op.create_index('idx_model_registry_status', 'model_registry', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('FORECAST', 'TRAINING', 'ALERT', 'INVENTORY', 'SYSTEM', 'SYNC', 'UPLOAD', 'PROCESSING', 'VALIDATION', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), nullable=True),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_entity', 'notifications', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_notification_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['type'], unique=False)
    op.create_index('idx_notification_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sync_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.Enum('CONNECTING', 'DOWNLOADING', 'VALIDATING', 'SAVING', 'COMPLETED', name='syncjobstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_job_steps_job', 'sync_job_steps', ['sync_job_id'], unique=False)
    op.create_index('idx_sync_job_steps_status', 'sync_job_steps', ['status'], unique=False)
    op.create_index(op.f('ix_sync_job_steps_id'), 'sync_job_steps', ['id'], unique=False)
    op.create_index(op.f('ix_sync_job_steps_sync_job_id'), 'sync_job_steps', ['sync_job_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('unique_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('processing_progress', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_processing_status', 'uploads', ['processing_status'], unique=False)
    op.create_index('idx_upload_status', 'uploads', ['status'], unique=False)
    op.create_index('idx_upload_uploaded_at', 'uploads', ['uploaded_at'], unique=False)
    op.create_index('idx_upload_uploaded_by', 'uploads', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_table('forecast_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('model_registry_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='forecastjobstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('current_step_name', sa.String(length=100), nullable=True),
    sa.Column('failed_step', sa.Integer(), nullable=True),
    sa.Column('failed_step_name', sa.String(length=100), nullable=True),
    sa.Column('current_step_message', sa.String(length=255), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('remaining_seconds', sa.Float(), nullable=True),
    sa.Column('forecast_start_date', sa.DateTime(), nullable=True),
    sa.Column('forecast_end_date', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_jobs_created_at', 'forecast_jobs', ['created_at'], unique=False)
    op.create_index('idx_forecast_jobs_model_registry_id', 'forecast_jobs', ['model_registry_id'], unique=False)
    op.create_index('idx_forecast_jobs_region', 'forecast_jobs', ['region'], unique=False)
    op.create_index('idx_forecast_jobs_sku', 'forecast_jobs', ['sku'], unique=False)
    op.create_index('idx_forecast_jobs_status', 'forecast_jobs', ['status'], unique=False)
    op.create_index('idx_forecast_jobs_upload_id', 'forecast_jobs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_forecast_jobs_id'), 'forecast_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_jobs_job_id'), 'forecast_jobs', ['job_id'], unique=True)
    op.create_table('forecast_metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_history_date', 'forecast_metric_history', ['date'], unique=False)
    op.create_index('idx_metric_history_model', 'forecast_metric_history', ['model_id'], unique=False)
    op.create_index('idx_metric_history_model_type', 'forecast_metric_history', ['model_type'], unique=False)
    op.create_index(op.f('ix_forecast_metric_history_id'), 'forecast_metric_history', ['id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('dataset_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='processingjobstatus'), nullable=True),
    sa.Column('current_step', sa.Enum('INGESTION', 'SCHEMA_VALIDATION', 'MISSING_IMPUTATION', 'OUTLIER_DETECTION', 'NORMALIZATION', 'FEATURE_ENGINEERING', 'AGGREGATION', 'COMPLETE', name='processingjobstep'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('records_loaded', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('eta_seconds', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_jobs_created_at', 'processing_jobs', ['created_at'], unique=False)
    op.create_index('idx_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('idx_processing_jobs_upload', 'processing_jobs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('rows_validated', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_synclog_datasource', 'sync_logs', ['datasource_id'], unique=False)
    op.create_index('idx_synclog_started', 'sync_logs', ['started_at'], unique=False)
    op.create_index('idx_synclog_status', 'sync_logs', ['status'], unique=False)
    op.create_index('idx_synclog_upload', 'sync_logs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_table('training_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_registry_id', sa.String(length=36), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=True),
    sa.Column('seasonality', sa.Boolean(), nullable=True),
    sa.Column('validation_split', sa.Float(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('default_dataset', sa.String(length=255), nullable=True),
    sa.Column('default_region', sa.String(length=100), nullable=True),
    sa.Column('default_sku', sa.String(length=100), nullable=True),
    sa.Column('default_warehouse', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('accuracy_threshold', sa.Float(), nullable=True),
    sa.Column('minimum_records', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_config_enabled', 'training_configurations', ['enabled'], unique=False)
    op.create_index('idx_training_config_frequency', 'training_configurations', ['frequency'], unique=False)
    op.create_index('idx_training_config_model', 'training_configurations', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_training_configurations_id'), 'training_configurations', ['id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('model_registry_id', sa.String(length=36), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='trainingstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('current_step_name', sa.String(length=100), nullable=True),
    sa.Column('failed_step', sa.Integer(), nullable=True),
    sa.Column('failed_step_name', sa.String(length=100), nullable=True),
    sa.Column('current_step_message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('remaining_time', sa.Float(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('worker_name', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('csv_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_training_jobs_created_at', 'training_jobs', ['created_at'], unique=False)
    op.create_index('idx_training_jobs_model_registry_id', 'training_jobs', ['model_registry_id'], unique=False)
    op.create_index('idx_training_jobs_model_type', 'training_jobs', ['model_type'], unique=False)
    op.create_index('idx_training_jobs_status', 'training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_training_jobs_job_id'), 'training_jobs', ['job_id'], unique=False)
    op.create_table('upload_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='uploadjobstatus'), nullable=True),
    sa.Column('current_step', sa.Enum('UPLOAD', 'READ', 'VALIDATE', 'STORE', 'COMPLETE', name='uploadjobstep'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_total', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_jobs_created_at', 'upload_jobs', ['created_at'], unique=False)
    op.create_index('idx_upload_jobs_status', 'upload_jobs', ['status'], unique=False)
    op.create_index('idx_upload_jobs_upload', 'upload_jobs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_id'), 'upload_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_job_id'), 'upload_jobs', ['job_id'], unique=True)
    op.create_table('forecast_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_job_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('LOADING_DATA', 'LOADING_MODEL', 'VALIDATING_DATA', 'RUNNING_MODEL', 'GENERATING_OUTPUT', 'SAVING_RESULTS', 'COMPLETED', name='forecastjobstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_job_steps_job', 'forecast_job_steps', ['forecast_job_id'], unique=False)
    op.create_index('idx_forecast_job_steps_status', 'forecast_job_steps', ['status'], unique=False)
    op.create_index(op.f('ix_forecast_job_steps_forecast_job_id'), 'forecast_job_steps', ['forecast_job_id'], unique=False)
    op.create_index(op.f('ix_forecast_job_steps_id'), 'forecast_job_steps', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_job_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=True),
    sa.Column('is_peak', sa.Boolean(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_results_date', 'forecast_results', ['forecast_date'], unique=False)
    op.create_index('idx_forecast_results_is_forecast', 'forecast_results', ['is_forecast'], unique=False)
    op.create_index('idx_forecast_results_job', 'forecast_results', ['forecast_job_id'], unique=False)
    op.create_index('idx_forecast_results_sku', 'forecast_results', ['sku'], unique=False)
    op.create_index(op.f('ix_forecast_results_forecast_job_id'), 'forecast_results', ['forecast_job_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_table('processing_generated_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_generated_features_id'), 'processing_generated_features', ['id'], unique=False)
    op.create_index(op.f('ix_processing_generated_features_processing_job_id'), 'processing_generated_features', ['processing_job_id'], unique=False)
    op.create_table('processing_job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_logs_job', 'processing_job_logs', ['processing_job_id'], unique=False)
    op.create_index('idx_processing_logs_level', 'processing_job_logs', ['level'], unique=False)
    op.create_index('idx_processing_logs_timestamp', 'processing_job_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_processing_job_logs_id'), 'processing_job_logs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_job_logs_processing_job_id'), 'processing_job_logs', ['processing_job_id'], unique=False)
    op.create_table('processing_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('INGESTION', 'SCHEMA_VALIDATION', 'MISSING_IMPUTATION', 'OUTLIER_DETECTION', 'NORMALIZATION', 'FEATURE_ENGINEERING', 'AGGREGATION', 'COMPLETE', name='processingjobstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_job_steps_id'), 'processing_job_steps', ['id'], unique=False)
    op.create_index(op.f('ix_processing_job_steps_processing_job_id'), 'processing_job_steps', ['processing_job_id'], unique=False)
    op.create_table('processing_outlier_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('total_outliers', sa.Integer(), nullable=True),
    sa.Column('removed', sa.Integer(), nullable=True),
    sa.Column('capped', sa.Integer(), nullable=True),
    sa.Column('normal_values', sa.Integer(), nullable=True),
    sa.Column('percentage_removed', sa.Float(), nullable=True),
    sa.Column('percentage_capped', sa.Float(), nullable=True),
    sa.Column('spike_rows', sa.JSON(), nullable=True),
    sa.Column('normal_points', sa.JSON(), nullable=True),
    sa.Column('outlier_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_outlier_results_id'), 'processing_outlier_results', ['id'], unique=False)
    op.create_index(op.f('ix_processing_outlier_results_processing_job_id'), 'processing_outlier_results', ['processing_job_id'], unique=False)
    op.create_table('raw_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_inventory_datasource', 'raw_inventory', ['datasource_id'], unique=False)
    op.create_index('idx_raw_inventory_sku', 'raw_inventory', ['sku'], unique=False)
    op.create_index('idx_raw_inventory_sync', 'raw_inventory', ['sync_id'], unique=False)
    op.create_index('idx_raw_inventory_upload', 'raw_inventory', ['upload_id'], unique=False)
    op.create_index(op.f('ix_raw_inventory_id'), 'raw_inventory', ['id'], unique=False)
    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_products_datasource', 'raw_products', ['datasource_id'], unique=False)
    op.create_index('idx_raw_products_sku', 'raw_products', ['sku'], unique=False)
    op.create_index('idx_raw_products_sync', 'raw_products', ['sync_id'], unique=False)
    op.create_index('idx_raw_products_upload', 'raw_products', ['upload_id'], unique=False)
    op.create_index(op.f('ix_raw_products_id'), 'raw_products', ['id'], unique=False)
    op.create_table('raw_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_sales_datasource', 'raw_sales', ['datasource_id'], unique=False)
    op.create_index('idx_raw_sales_date', 'raw_sales', ['date'], unique=False)
    op.create_index('idx_raw_sales_sku', 'raw_sales', ['sku'], unique=False)
    op.create_index('idx_raw_sales_sync', 'raw_sales', ['sync_id'], unique=False)
    op.create_index('idx_raw_sales_upload', 'raw_sales', ['upload_id'], unique=False)
    op.create_index(op.f('ix_raw_sales_id'), 'raw_sales', ['id'], unique=False)
    op.create_table('raw_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('min_order', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_suppliers_datasource', 'raw_suppliers', ['datasource_id'], unique=False)
    op.create_index('idx_raw_suppliers_sync', 'raw_suppliers', ['sync_id'], unique=False)
    op.create_index('idx_raw_suppliers_upload', 'raw_suppliers', ['upload_id'], unique=False)
    op.create_index(op.f('ix_raw_suppliers_id'), 'raw_suppliers', ['id'], unique=False)
    op.create_table('training_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.String(length=36), nullable=True),
    sa.Column('model_registry_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accuracy_before', sa.Float(), nullable=True),
    sa.Column('accuracy_after', sa.Float(), nullable=True),
    sa.Column('improvement_percentage', sa.Float(), nullable=True),
    sa.Column('rmse_before', sa.Float(), nullable=True),
    sa.Column('rmse_after', sa.Float(), nullable=True),
    sa.Column('mae_before', sa.Float(), nullable=True),
    sa.Column('mae_after', sa.Float(), nullable=True),
    sa.Column('mape_before', sa.Float(), nullable=True),
    sa.Column('mape_after', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trained_by', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.job_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_history_model_registry_id', 'training_history', ['model_registry_id'], unique=False)
    op.create_index('idx_training_history_trained_at', 'training_history', ['trained_at'], unique=False)
    op.create_index('idx_training_history_training_job_id', 'training_history', ['training_job_id'], unique=False)
    op.create_index('idx_training_history_version', 'training_history', ['version'], unique=False)
    op.create_index(op.f('ix_training_history_id'), 'training_history', ['id'], unique=False)
    op.create_table('training_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.String(length=36), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('PROCESSING_DATA', 'VALIDATION', 'TRAINING', 'EVALUATION', 'SAVING_MODEL', 'COMPLETED', name='trainingstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_job_steps_id'), 'training_job_steps', ['id'], unique=False)
    op.create_index(op.f('ix_training_job_steps_training_job_id'), 'training_job_steps', ['training_job_id'], unique=False)
    op.create_table('upload_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_job_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.Enum('UPLOAD', 'READ', 'VALIDATE', 'STORE', 'COMPLETE', name='uploadjobstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_job_id'], ['upload_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_job_steps_id'), 'upload_job_steps', ['id'], unique=False)
    op.create_index(op.f('ix_upload_job_steps_upload_job_id'), 'upload_job_steps', ['upload_job_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('ignored_reason', sa.Text(), nullable=True),
    sa.Column('fixed_reason', sa.Text(), nullable=True),
    sa.Column('fixed_by', sa.Integer(), nullable=True),
    sa.Column('fixed_time', sa.DateTime(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['fixed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_valerror_datasource', 'validation_errors', ['datasource_id'], unique=False)
    op.create_index('idx_valerror_is_fixed', 'validation_errors', ['is_fixed'], unique=False)
    op.create_index('idx_valerror_is_ignored', 'validation_errors', ['is_ignored'], unique=False)
    op.create_index('idx_valerror_severity', 'validation_errors', ['severity'], unique=False)
    op.create_index('idx_valerror_status', 'validation_errors', ['status'], unique=False)
    op.create_index('idx_valerror_sync', 'validation_errors', ['sync_id'], unique=False)
    op.create_index('idx_valerror_upload', 'validation_errors', ['upload_id'], unique=False)
    op.create_index(op.f('ix_validation_errors_id'), 'validation_errors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_errors_id'), table_name='validation_errors')
    op.drop_index('idx_valerror_upload', table_name='validation_errors')
    op.drop_index('idx_valerror_sync', table_name='validation_errors')
    op.drop_index('idx_valerror_status', table_name='validation_errors')
    op.drop_index('idx_valerror_severity', table_name='validation_errors')
    op.drop_index('idx_valerror_is_ignored', table_name='validation_errors')
    op.drop_index('idx_valerror_is_fixed', table_name='validation_errors')
    op.drop_index('idx_valerror_datasource', table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_upload_job_steps_upload_job_id'), table_name='upload_job_steps')
    op.drop_index(op.f('ix_upload_job_steps_id'), table_name='upload_job_steps')
    op.drop_table('upload_job_steps')
    op.drop_index(op.f('ix_training_job_steps_training_job_id'), table_name='training_job_steps')
    op.drop_index(op.f('ix_training_job_steps_id'), table_name='training_job_steps')
    op.drop_table('training_job_steps')
    op.drop_index(op.f('ix_training_history_id'), table_name='training_history')
    op.drop_index('idx_training_history_version', table_name='training_history')
    op.drop_index('idx_training_history_training_job_id', table_name='training_history')
    op.drop_index('idx_training_history_trained_at', table_name='training_history')
    op.drop_index('idx_training_history_model_registry_id', table_name='training_history')
    op.drop_table('training_history')
    op.drop_index(op.f('ix_raw_suppliers_id'), table_name='raw_suppliers')
    op.drop_index('idx_raw_suppliers_upload', table_name='raw_suppliers')
    op.drop_index('idx_raw_suppliers_sync', table_name='raw_suppliers')
    op.drop_index('idx_raw_suppliers_datasource', table_name='raw_suppliers')
    op.drop_table('raw_suppliers')
    op.drop_index(op.f('ix_raw_sales_id'), table_name='raw_sales')
    op.drop_index('idx_raw_sales_upload', table_name='raw_sales')
    op.drop_index('idx_raw_sales_sync', table_name='raw_sales')
    op.drop_index('idx_raw_sales_sku', table_name='raw_sales')
    op.drop_index('idx_raw_sales_date', table_name='raw_sales')
    op.drop_index('idx_raw_sales_datasource', table_name='raw_sales')
    op.drop_table('raw_sales')
    op.drop_index(op.f('ix_raw_products_id'), table_name='raw_products')
    op.drop_index('idx_raw_products_upload', table_name='raw_products')
    op.drop_index('idx_raw_products_sync', table_name='raw_products')
    op.drop_index('idx_raw_products_sku', table_name='raw_products')
    op.drop_index('idx_raw_products_datasource', table_name='raw_products')
    op.drop_table('raw_products')
    op.drop_index(op.f('ix_raw_inventory_id'), table_name='raw_inventory')
    op.drop_index('idx_raw_inventory_upload', table_name='raw_inventory')
    op.drop_index('idx_raw_inventory_sync', table_name='raw_inventory')
    op.drop_index('idx_raw_inventory_sku', table_name='raw_inventory')
    op.drop_index('idx_raw_inventory_datasource', table_name='raw_inventory')
    op.drop_table('raw_inventory')
    op.drop_index(op.f('ix_processing_outlier_results_processing_job_id'), table_name='processing_outlier_results')
    op.drop_index(op.f('ix_processing_outlier_results_id'), table_name='processing_outlier_results')
    op.drop_table('processing_outlier_results')
    op.drop_index(op.f('ix_processing_job_steps_processing_job_id'), table_name='processing_job_steps')
    op.drop_index(op.f('ix_processing_job_steps_id'), table_name='processing_job_steps')
    op.drop_table('processing_job_steps')
    op.drop_index(op.f('ix_processing_job_logs_processing_job_id'), table_name='processing_job_logs')
    op.drop_index(op.f('ix_processing_job_logs_id'), table_name='processing_job_logs')
    op.drop_index('idx_processing_logs_timestamp', table_name='processing_job_logs')
    op.drop_index('idx_processing_logs_level', table_name='processing_job_logs')
    op.drop_index('idx_processing_logs_job', table_name='processing_job_logs')
    op.drop_table('processing_job_logs')
    op.drop_index(op.f('ix_processing_generated_features_processing_job_id'), table_name='processing_generated_features')
    op.drop_index(op.f('ix_processing_generated_features_id'), table_name='processing_generated_features')
    op.drop_table('processing_generated_features')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_job_id'), table_name='forecast_results')
    op.drop_index('idx_forecast_results_sku', table_name='forecast_results')
    op.drop_index('idx_forecast_results_job', table_name='forecast_results')
    op.drop_index('idx_forecast_results_is_forecast', table_name='forecast_results')
    op.drop_index('idx_forecast_results_date', table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_job_steps_id'), table_name='forecast_job_steps')
    op.drop_index(op.f('ix_forecast_job_steps_forecast_job_id'), table_name='forecast_job_steps')
    op.drop_index('idx_forecast_job_steps_status', table_name='forecast_job_steps')
    op.drop_index('idx_forecast_job_steps_job', table_name='forecast_job_steps')
    op.drop_table('forecast_job_steps')
    op.drop_index(op.f('ix_upload_jobs_job_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_id'), table_name='upload_jobs')
    op.drop_index('idx_upload_jobs_upload', table_name='upload_jobs')
    op.drop_index('idx_upload_jobs_status', table_name='upload_jobs')
    op.drop_index('idx_upload_jobs_created_at', table_name='upload_jobs')
    op.drop_table('upload_jobs')
    op.drop_index(op.f('ix_training_jobs_job_id'), table_name='training_jobs')
    op.drop_index('idx_training_jobs_status', table_name='training_jobs')
    op.drop_index('idx_training_jobs_model_type', table_name='training_jobs')
    op.drop_index('idx_training_jobs_model_registry_id', table_name='training_jobs')
    op.drop_index('idx_training_jobs_created_at', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_training_configurations_id'), table_name='training_configurations')
    op.drop_index('idx_training_config_model', table_name='training_configurations')
    op.drop_index('idx_training_config_frequency', table_name='training_configurations')
    op.drop_index('idx_training_config_enabled', table_name='training_configurations')
    op.drop_table('training_configurations')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_index('idx_synclog_upload', table_name='sync_logs')
    op.drop_index('idx_synclog_status', table_name='sync_logs')
    op.drop_index('idx_synclog_started', table_name='sync_logs')
    op.drop_index('idx_synclog_datasource', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_upload', table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_created_at', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_forecast_metric_history_id'), table_name='forecast_metric_history')
    op.drop_index('idx_metric_history_model_type', table_name='forecast_metric_history')
    op.drop_index('idx_metric_history_model', table_name='forecast_metric_history')
    op.drop_index('idx_metric_history_date', table_name='forecast_metric_history')
    op.drop_table('forecast_metric_history')
    op.drop_index(op.f('ix_forecast_jobs_job_id'), table_name='forecast_jobs')
    op.drop_index(op.f('ix_forecast_jobs_id'), table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_upload_id', table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_status', table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_sku', table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_region', table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_model_registry_id', table_name='forecast_jobs')
    op.drop_index('idx_forecast_jobs_created_at', table_name='forecast_jobs')
    op.drop_table('forecast_jobs')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_index('idx_upload_uploaded_by', table_name='uploads')
    op.drop_index('idx_upload_uploaded_at', table_name='uploads')
    op.drop_index('idx_upload_status', table_name='uploads')
    op.drop_index('idx_upload_processing_status', table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_sync_job_steps_sync_job_id'), table_name='sync_job_steps')
    op.drop_index(op.f('ix_sync_job_steps_id'), table_name='sync_job_steps')
    op.drop_index('idx_sync_job_steps_status', table_name='sync_job_steps')
    op.drop_index('idx_sync_job_steps_job', table_name='sync_job_steps')
    op.drop_table('sync_job_steps')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user_id', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_status', table_name='notifications')
    op.drop_index('idx_notification_entity', table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_model_registry_status', table_name='model_registry')
    op.drop_index('idx_model_registry_model_type', table_name='model_registry')
    op.drop_index('idx_model_registry_is_favorite', table_name='model_registry')
    op.drop_index('idx_model_registry_is_default', table_name='model_registry')
    op.drop_index('idx_model_registry_is_active', table_name='model_registry')
    op.drop_index('idx_model_registry_deployment_status', table_name='model_registry')
    op.drop_index('idx_model_registry_best_accuracy', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_jobs_job_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_triggered_by', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_status', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_datasource', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_created_at', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_connection_history_id'), table_name='connection_history')
    op.drop_index('idx_connection_history_status', table_name='connection_history')
    op.drop_index('idx_connection_history_started_at', table_name='connection_history')
    op.drop_index('idx_connection_history_datasource', table_name='connection_history')
    op.drop_table('connection_history')
    op.drop_index(op.f('ix_warehouse_inventory_warehouse'), table_name='warehouse_inventory')
    op.drop_index(op.f('ix_warehouse_inventory_sku'), table_name='warehouse_inventory')
    op.drop_index(op.f('ix_warehouse_inventory_id'), table_name='warehouse_inventory')
    op.drop_table('warehouse_inventory')
    op.drop_index(op.f('ix_scheduler_history_id'), table_name='scheduler_history')
    op.drop_index('idx_scheduler_history_type', table_name='scheduler_history')
    op.drop_index('idx_scheduler_history_status', table_name='scheduler_history')
    op.drop_index('idx_scheduler_history_started', table_name='scheduler_history')
    op.drop_index('idx_scheduler_history_job', table_name='scheduler_history')
    op.drop_table('scheduler_history')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_safety_stock_calculations_warehouse'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_sku'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_id'), table_name='safety_stock_calculations')
    op.drop_table('safety_stock_calculations')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_reorder_points_warehouse'), table_name='reorder_points')
    op.drop_index(op.f('ix_reorder_points_sku'), table_name='reorder_points')
    op.drop_index(op.f('ix_reorder_points_id'), table_name='reorder_points')
    op.drop_table('reorder_points')
    op.drop_index(op.f('ix_recommendations_sku'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_otp_records_user_email'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_id'), table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_index(op.f('ix_inventory_transfers_sku'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_id'), table_name='inventory_transfers')
    op.drop_table('inventory_transfers')
    op.drop_index(op.f('ix_inventory_skus_sku'), table_name='inventory_skus')
    op.drop_index(op.f('ix_inventory_skus_id'), table_name='inventory_skus')
    op.drop_table('inventory_skus')
    op.drop_index(op.f('ix_excess_stock_warehouse'), table_name='excess_stock')
    op.drop_index(op.f('ix_excess_stock_sku'), table_name='excess_stock')
    op.drop_index(op.f('ix_excess_stock_id'), table_name='excess_stock')
    op.drop_table('excess_stock')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_index('idx_datasource_type', table_name='data_sources')
    op.drop_index('idx_datasource_sync_frequency', table_name='data_sources')
    op.drop_index('idx_datasource_status', table_name='data_sources')
    op.drop_index('idx_datasource_health_score', table_name='data_sources')
    op.drop_index('idx_datasource_health', table_name='data_sources')
    op.drop_index('idx_datasource_created_at', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_auth_audit_logs_id'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_event_type'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_email'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_created_at'), table_name='auth_audit_logs')
    op.drop_table('auth_audit_logs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
