"""recommendation updated

Revision ID: 5eb269250198
Revises: d11662293647
Create Date: 2026-07-22 14:18:53.556149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5eb269250198'
down_revision: Union[str, Sequence[str], None] = 'd11662293647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_job_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_job_internal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='recommendationjobstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('current_step_name', sa.String(length=100), nullable=True),
    sa.Column('failed_step', sa.Integer(), nullable=True),
    sa.Column('failed_step_name', sa.String(length=100), nullable=True),
    sa.Column('current_step_message', sa.String(length=255), nullable=True),
    sa.Column('total_recommendations', sa.Integer(), nullable=True),
    sa.Column('saved_recommendations', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('forecast_summary', sa.JSON(), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=True),
    sa.Column('generator_version', sa.String(length=20), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('remaining_seconds', sa.Float(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('job_duration', sa.Float(), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['forecast_job_internal_id'], ['forecast_jobs.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_jobs_created_at', 'recommendation_jobs', ['created_at'], unique=False)
    op.create_index('idx_rec_jobs_created_by', 'recommendation_jobs', ['created_by'], unique=False)
    op.create_index('idx_rec_jobs_forecast_job_id', 'recommendation_jobs', ['forecast_job_id'], unique=False)
    op.create_index('idx_rec_jobs_started_by', 'recommendation_jobs', ['started_by'], unique=False)
    op.create_index('idx_rec_jobs_status', 'recommendation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_recommendation_jobs_id'), 'recommendation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_jobs_job_id'), 'recommendation_jobs', ['job_id'], unique=True)
    op.create_table('recommendation_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_job_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('LOADING_FORECAST', 'LOADING_SUMMARY', 'READING_RESULTS', 'DEMAND_ANALYSIS', 'INVENTORY_ANALYSIS', 'RISK_ANALYSIS', 'GENERATING_RECOMMENDATIONS', 'REMOVING_DUPLICATES', 'VALIDATING', 'SAVING_RECOMMENDATIONS', 'NOTIFYING', 'REFRESHING_DASHBOARD', 'COMPLETED', name='recommendationjobstep'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_job_id'], ['recommendation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_job_steps_job', 'recommendation_job_steps', ['recommendation_job_id'], unique=False)
    op.create_index('idx_rec_job_steps_status', 'recommendation_job_steps', ['status'], unique=False)
    op.create_index(op.f('ix_recommendation_job_steps_id'), 'recommendation_job_steps', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_job_steps_recommendation_job_id'), 'recommendation_job_steps', ['recommendation_job_id'], unique=False)
    op.create_table('recommendation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_job_id', sa.Integer(), nullable=True),
    sa.Column('forecast_job_id', sa.String(length=36), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('REORDER', 'INVENTORY_OPTIMIZATION', 'PROCUREMENT', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT', 'SUPPLIER_MANAGEMENT', 'PRICING', 'DEMAND_MANAGEMENT', 'RISK_MANAGEMENT', name='recommendationresultcategory'), nullable=True),
    sa.Column('recommendation_type', sa.Enum('REORDER', 'PROCUREMENT', 'TRANSFER_STOCK', 'WAREHOUSE_OPTIMIZATION', 'SAFETY_STOCK', 'SUPPLIER_DISCOUNT', 'BULK_PURCHASE', 'OVERSTOCK', 'CRITICAL_ALERT', 'INVENTORY_OPTIMIZATION', 'PROMOTION', 'PRICE_REDUCTION', 'DEMAND_SPIKE', 'DEMAND_DROP', 'SUPPLIER_RISK', 'SEASONAL_STOCK', 'LOW_CONFIDENCE_ALERT', name='recommendationresulttype'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='recommendationresultpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'IGNORED', 'IN_PROGRESS', 'FAILED', name='recommendationresultstatus'), nullable=False),
    sa.Column('business_reason', sa.Text(), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('recommended_quantity', sa.Float(), nullable=False),
    sa.Column('lead_time', sa.String(length=50), nullable=True),
    sa.Column('inventory_days', sa.Float(), nullable=True),
    sa.Column('holding_cost', sa.Float(), nullable=True),
    sa.Column('stockout_probability', sa.Float(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('estimated_revenue', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_loss', sa.Float(), nullable=True),
    sa.Column('expected_impact', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('forecast_summary', sa.JSON(), nullable=True),
    sa.Column('forecast_accuracy', sa.Float(), nullable=True),
    sa.Column('forecast_window', sa.Integer(), nullable=True),
    sa.Column('related_forecast', sa.JSON(), nullable=True),
    sa.Column('action_label', sa.String(length=255), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('forecast_value', sa.Float(), nullable=True),
    sa.Column('current_demand', sa.Float(), nullable=True),
    sa.Column('predicted_demand', sa.Float(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_discount_available', sa.Boolean(), nullable=True),
    sa.Column('discount_days', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('key_details', sa.JSON(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('ignored_by', sa.Integer(), nullable=True),
    sa.Column('ignored_at', sa.DateTime(), nullable=True),
    sa.Column('ignored_reason', sa.Text(), nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['ignored_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_job_id'], ['recommendation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_result_category', 'recommendation_results', ['category'], unique=False)
    op.create_index('idx_rec_result_created_at', 'recommendation_results', ['created_at'], unique=False)
    op.create_index('idx_rec_result_forecast_job', 'recommendation_results', ['forecast_job_id'], unique=False)
    op.create_index('idx_rec_result_job', 'recommendation_results', ['recommendation_job_id'], unique=False)
    op.create_index('idx_rec_result_priority', 'recommendation_results', ['priority'], unique=False)
    op.create_index('idx_rec_result_recommendation_score', 'recommendation_results', ['recommendation_score'], unique=False)
    op.create_index('idx_rec_result_sku', 'recommendation_results', ['sku'], unique=False)
    op.create_index('idx_rec_result_status', 'recommendation_results', ['status'], unique=False)
    op.create_index('idx_rec_result_supplier_name', 'recommendation_results', ['supplier_name'], unique=False)
    op.create_index('idx_rec_result_type', 'recommendation_results', ['recommendation_type'], unique=False)
    op.create_index('idx_rec_result_warehouse', 'recommendation_results', ['warehouse'], unique=False)
    op.create_index(op.f('ix_recommendation_results_id'), 'recommendation_results', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_results_recommendation_job_id'), 'recommendation_results', ['recommendation_job_id'], unique=False)
    op.create_index(op.f('ix_recommendation_results_sku'), 'recommendation_results', ['sku'], unique=False)
    op.create_index(op.f('ix_recommendation_results_warehouse'), 'recommendation_results', ['warehouse'], unique=False)
    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_job_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('forecast_value', sa.Float(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_job_id'], ['recommendation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_history_action', 'recommendation_history', ['action'], unique=False)
    op.create_index('idx_rec_history_performed_at', 'recommendation_history', ['performed_at'], unique=False)
    op.create_index('idx_rec_history_performed_by', 'recommendation_history', ['performed_by'], unique=False)
    op.create_index('idx_rec_history_recommendation_id', 'recommendation_history', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_id'), 'recommendation_history', ['id'], unique=False)
    op.drop_index(op.f('idx_recommendation_category'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_created_at'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_priority'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_sku'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_status'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendation_warehouse'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_sku'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('recommendation_type', mysql.ENUM('CRITICAL', 'HIGH', 'REORDER', 'PROCUREMENT', 'INVENTORY_OPTIMIZATION', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT'), nullable=False),
    sa.Column('priority', mysql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'EXECUTED', 'IGNORED', 'IN_PROGRESS'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.ENUM('REORDER', 'INVENTORY_OPTIMIZATION', 'PROCUREMENT', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT'), nullable=True),
    sa.Column('current_stock', mysql.FLOAT(), nullable=True),
    sa.Column('recommended_quantity', mysql.FLOAT(), nullable=False),
    sa.Column('lead_time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estimated_savings', mysql.FLOAT(), nullable=True),
    sa.Column('expected_impact', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ai_confidence', mysql.FLOAT(), nullable=True),
    sa.Column('action_label', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('warehouse', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('forecast_value', mysql.FLOAT(), nullable=True),
    sa.Column('current_demand', mysql.FLOAT(), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('supplier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_discount_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('discount_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_details', mysql.JSON(), nullable=True),
    sa.Column('executed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_at', mysql.DATETIME(), nullable=True),
    sa.Column('ignored_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ignored_at', mysql.DATETIME(), nullable=True),
    sa.Column('ignored_reason', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('recommendations_ibfk_2')),
    sa.ForeignKeyConstraint(['ignored_by'], ['users.id'], name=op.f('recommendations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_recommendations_sku'), 'recommendations', ['sku'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('idx_recommendation_warehouse'), 'recommendations', ['warehouse'], unique=False)
    op.create_index(op.f('idx_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('idx_recommendation_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('idx_recommendation_sku'), 'recommendations', ['sku'], unique=False)
    op.create_index(op.f('idx_recommendation_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('idx_recommendation_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('idx_recommendation_category'), 'recommendations', ['category'], unique=False)
    op.drop_index(op.f('ix_recommendation_history_id'), table_name='recommendation_history')
    op.drop_index('idx_rec_history_recommendation_id', table_name='recommendation_history')
    op.drop_index('idx_rec_history_performed_by', table_name='recommendation_history')
    op.drop_index('idx_rec_history_performed_at', table_name='recommendation_history')
    op.drop_index('idx_rec_history_action', table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_index(op.f('ix_recommendation_results_warehouse'), table_name='recommendation_results')
    op.drop_index(op.f('ix_recommendation_results_sku'), table_name='recommendation_results')
    op.drop_index(op.f('ix_recommendation_results_recommendation_job_id'), table_name='recommendation_results')
    op.drop_index(op.f('ix_recommendation_results_id'), table_name='recommendation_results')
    op.drop_index('idx_rec_result_warehouse', table_name='recommendation_results')
    op.drop_index('idx_rec_result_type', table_name='recommendation_results')
    op.drop_index('idx_rec_result_supplier_name', table_name='recommendation_results')
    op.drop_index('idx_rec_result_status', table_name='recommendation_results')
    op.drop_index('idx_rec_result_sku', table_name='recommendation_results')
    op.drop_index('idx_rec_result_recommendation_score', table_name='recommendation_results')
    op.drop_index('idx_rec_result_priority', table_name='recommendation_results')
    op.drop_index('idx_rec_result_job', table_name='recommendation_results')
    op.drop_index('idx_rec_result_forecast_job', table_name='recommendation_results')
    op.drop_index('idx_rec_result_created_at', table_name='recommendation_results')
    op.drop_index('idx_rec_result_category', table_name='recommendation_results')
    op.drop_table('recommendation_results')
    op.drop_index(op.f('ix_recommendation_job_steps_recommendation_job_id'), table_name='recommendation_job_steps')
    op.drop_index(op.f('ix_recommendation_job_steps_id'), table_name='recommendation_job_steps')
    op.drop_index('idx_rec_job_steps_status', table_name='recommendation_job_steps')
    op.drop_index('idx_rec_job_steps_job', table_name='recommendation_job_steps')
    op.drop_table('recommendation_job_steps')
    op.drop_index(op.f('ix_recommendation_jobs_job_id'), table_name='recommendation_jobs')
    op.drop_index(op.f('ix_recommendation_jobs_id'), table_name='recommendation_jobs')
    op.drop_index('idx_rec_jobs_status', table_name='recommendation_jobs')
    op.drop_index('idx_rec_jobs_started_by', table_name='recommendation_jobs')
    op.drop_index('idx_rec_jobs_forecast_job_id', table_name='recommendation_jobs')
    op.drop_index('idx_rec_jobs_created_by', table_name='recommendation_jobs')
    op.drop_index('idx_rec_jobs_created_at', table_name='recommendation_jobs')
    op.drop_table('recommendation_jobs')
    # ### end Alembic commands ###
