"""commited

Revision ID: c369be827cba
Revises: 79fb6dd76fc4
Create Date: 2026-07-27 10:40:08.698966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c369be827cba'
down_revision: Union[str, Sequence[str], None] = '79fb6dd76fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_stock_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('max_daily_demand', sa.Float(), nullable=False),
    sa.Column('avg_lead_time_days', sa.Float(), nullable=False),
    sa.Column('max_lead_time_days', sa.Float(), nullable=False),
    sa.Column('service_level', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('demand_variability', sa.Float(), nullable=True),
    sa.Column('lead_time_variability', sa.Float(), nullable=True),
    sa.Column('safety_stock_value', sa.Float(), nullable=False),
    sa.Column('reorder_point_value', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('calculated_by', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safety_stock_calc_calculated_at', 'safety_stock_calculations', ['calculated_at'], unique=False)
    op.create_index('idx_safety_stock_calc_is_active', 'safety_stock_calculations', ['is_active'], unique=False)
    op.create_index('idx_safety_stock_calc_method', 'safety_stock_calculations', ['calculation_method'], unique=False)
    op.create_index('idx_safety_stock_calc_sku', 'safety_stock_calculations', ['sku'], unique=False)
    op.create_index('idx_safety_stock_calc_sku_warehouse', 'safety_stock_calculations', ['sku', 'warehouse'], unique=False)
    op.create_index('idx_safety_stock_calc_warehouse', 'safety_stock_calculations', ['warehouse'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_id'), 'safety_stock_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_sku'), 'safety_stock_calculations', ['sku'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_warehouse'), 'safety_stock_calculations', ['warehouse'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_stock_calculations_warehouse'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_sku'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_id'), table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_warehouse', table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_sku_warehouse', table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_sku', table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_method', table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_is_active', table_name='safety_stock_calculations')
    op.drop_index('idx_safety_stock_calc_calculated_at', table_name='safety_stock_calculations')
    op.drop_table('safety_stock_calculations')
    # ### end Alembic commands ###
