"""inventory and simulation

Revision ID: d11662293647
Revises: 7d1e558265c2
Create Date: 2026-07-21 12:41:37.458136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd11662293647'
down_revision: Union[str, Sequence[str], None] = '7d1e558265c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_alerts_created_at', 'inventory_alerts', ['created_at'], unique=False)
    op.create_index('idx_inventory_alerts_severity', 'inventory_alerts', ['severity'], unique=False)
    op.create_index('idx_inventory_alerts_sku', 'inventory_alerts', ['sku'], unique=False)
    op.create_index('idx_inventory_alerts_type', 'inventory_alerts', ['alert_type'], unique=False)
    op.create_index('idx_inventory_alerts_warehouse', 'inventory_alerts', ['warehouse'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_id'), 'inventory_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_sku'), 'inventory_alerts', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_warehouse'), 'inventory_alerts', ['warehouse'], unique=False)
    op.create_table('slow_moving_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('avg_daily_sales', sa.Float(), nullable=True),
    sa.Column('days_in_stock', sa.Float(), nullable=True),
    sa.Column('turnover_ratio', sa.Float(), nullable=True),
    sa.Column('last_sale_date', sa.DateTime(), nullable=True),
    sa.Column('slow_moving_level', sa.String(length=50), nullable=True),
    sa.Column('action_recommended', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slow_moving_level', 'slow_moving_inventory', ['slow_moving_level'], unique=False)
    op.create_index('idx_slow_moving_sku', 'slow_moving_inventory', ['sku'], unique=False)
    op.create_index('idx_slow_moving_warehouse', 'slow_moving_inventory', ['warehouse'], unique=False)
    op.create_index(op.f('ix_slow_moving_inventory_id'), 'slow_moving_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_slow_moving_inventory_sku'), 'slow_moving_inventory', ['sku'], unique=False)
    op.create_index(op.f('ix_slow_moving_inventory_warehouse'), 'slow_moving_inventory', ['warehouse'], unique=False)
    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('old_stock', sa.Float(), nullable=False),
    sa.Column('new_stock', sa.Float(), nullable=False),
    sa.Column('change_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_history_created_at', 'inventory_history', ['created_at'], unique=False)
    op.create_index('idx_inventory_history_reason', 'inventory_history', ['reason'], unique=False)
    op.create_index('idx_inventory_history_sku', 'inventory_history', ['sku'], unique=False)
    op.create_index('idx_inventory_history_warehouse', 'inventory_history', ['warehouse'], unique=False)
    op.create_index(op.f('ix_inventory_history_id'), 'inventory_history', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_history_sku'), 'inventory_history', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_history_warehouse'), 'inventory_history', ['warehouse'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_movements_created_at', 'inventory_movements', ['created_at'], unique=False)
    op.create_index('idx_inventory_movements_sku', 'inventory_movements', ['sku'], unique=False)
    op.create_index('idx_inventory_movements_type', 'inventory_movements', ['movement_type'], unique=False)
    op.create_index('idx_inventory_movements_warehouse', 'inventory_movements', ['warehouse'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_sku'), 'inventory_movements', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_movements_warehouse'), 'inventory_movements', ['warehouse'], unique=False)
    op.add_column('inventory_transfers', sa.Column('approval_status', sa.String(length=50), nullable=True))
    op.add_column('inventory_transfers', sa.Column('approved_by', sa.String(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('completed_by', sa.String(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('expected_arrival', sa.DateTime(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('actual_arrival', sa.DateTime(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('vehicle', sa.String(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('driver', sa.String(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('transfer_number', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'inventory_transfers', ['transfer_number'])
    op.add_column('recommendations', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('recommendations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('category', sa.Enum('REORDER', 'INVENTORY_OPTIMIZATION', 'PROCUREMENT', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT', name='recommendationcategory'), nullable=True))
    op.add_column('recommendations', sa.Column('current_stock', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('recommended_quantity', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('lead_time', sa.String(length=50), nullable=True))
    op.add_column('recommendations', sa.Column('estimated_savings', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('expected_impact', sa.String(length=255), nullable=True))
    op.add_column('recommendations', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('action_label', sa.String(length=255), nullable=True))
    op.add_column('recommendations', sa.Column('warehouse', sa.String(length=100), nullable=True))
    op.add_column('recommendations', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('recommendations', sa.Column('forecast_value', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('current_demand', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('predicted_demand', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('recommendations', sa.Column('supplier_discount_available', sa.Boolean(), nullable=True))
    op.add_column('recommendations', sa.Column('discount_days', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('key_details', sa.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('executed_by', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('executed_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('ignored_by', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('ignored_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('ignored_reason', sa.Text(), nullable=True))
    op.alter_column('recommendations', 'recommendation_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('CRITICAL', 'HIGH', 'REORDER', 'PROCUREMENT', 'INVENTORY_OPTIMIZATION', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT', name='recommendationtype'),
               existing_nullable=False)
    op.alter_column('recommendations', 'priority',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='recommendationpriority'),
               existing_nullable=False)
    op.alter_column('recommendations', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'EXECUTED', 'IGNORED', 'IN_PROGRESS', name='recommendationstatus'),
               existing_nullable=False)
    op.create_index('idx_recommendation_category', 'recommendations', ['category'], unique=False)
    op.create_index('idx_recommendation_created_at', 'recommendations', ['created_at'], unique=False)
    op.create_index('idx_recommendation_priority', 'recommendations', ['priority'], unique=False)
    op.create_index('idx_recommendation_sku', 'recommendations', ['sku'], unique=False)
    op.create_index('idx_recommendation_status', 'recommendations', ['status'], unique=False)
    op.create_index('idx_recommendation_type', 'recommendations', ['recommendation_type'], unique=False)
    op.create_index('idx_recommendation_warehouse', 'recommendations', ['warehouse'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'users', ['ignored_by'], ['id'])
    op.create_foreign_key(None, 'recommendations', 'users', ['executed_by'], ['id'])
    op.drop_column('recommendations', 'suggested_action')
    op.drop_column('recommendations', 'quantity')
    op.add_column('scenario_comparisons', sa.Column('comparison_chart', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_labels', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_baseline', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_simulation', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_difference', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_labels', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_baseline', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_simulation', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_difference', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('all_skus', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('recommendation_ids', sa.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('summary_cards', sa.JSON(), nullable=True))
    op.add_column('scenario_runs', sa.Column('step_number', sa.Integer(), nullable=True))
    op.add_column('scenario_runs', sa.Column('total_steps', sa.Integer(), nullable=True))
    op.add_column('scenario_runs', sa.Column('logs', sa.JSON(), nullable=True))
    op.add_column('scenario_runs', sa.Column('estimated_completion', sa.DateTime(), nullable=True))
    op.add_column('scenarios', sa.Column('time_horizon', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('warehouse', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('scenarios', sa.Column('demand_surge', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('price_change', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('supply_delay', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('seasonal_impact', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('progress', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('forecast_model', sa.String(length=50), nullable=True))
    op.add_column('scenarios', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('executed_by', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('exported_by', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('scenarios', sa.Column('exported_at', sa.DateTime(), nullable=True))
    op.alter_column('scenarios', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'CREATED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scenariostatus'),
               existing_nullable=False)
    op.create_index('idx_scenario_category', 'scenarios', ['category'], unique=False)
    op.create_index('idx_scenario_created_at', 'scenarios', ['created_at'], unique=False)
    op.create_index('idx_scenario_created_by', 'scenarios', ['created_by'], unique=False)
    op.create_index('idx_scenario_forecast_model', 'scenarios', ['forecast_model'], unique=False)
    op.create_index('idx_scenario_last_run_status', 'scenarios', ['last_run_status'], unique=False)
    op.create_index('idx_scenario_region', 'scenarios', ['region'], unique=False)
    op.create_index('idx_scenario_sku', 'scenarios', ['sku'], unique=False)
    op.create_index('idx_scenario_status', 'scenarios', ['status'], unique=False)
    op.create_index('idx_scenario_warehouse', 'scenarios', ['warehouse'], unique=False)
    op.create_foreign_key(None, 'scenarios', 'users', ['exported_by'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'users', ['executed_by'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'users', ['created_by'], ['id'])
    op.add_column('warehouse_inventory', sa.Column('inventory_value', sa.Float(), nullable=True))
    op.create_index('idx_warehouse_inventory_inventory_value', 'warehouse_inventory', ['inventory_value'], unique=False)
    op.create_index('idx_warehouse_inventory_region', 'warehouse_inventory', ['region'], unique=False)
    op.create_index('idx_warehouse_inventory_sku', 'warehouse_inventory', ['sku'], unique=False)
    op.create_index('idx_warehouse_inventory_warehouse', 'warehouse_inventory', ['warehouse'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_warehouse_inventory_warehouse', table_name='warehouse_inventory')
    op.drop_index('idx_warehouse_inventory_sku', table_name='warehouse_inventory')
    op.drop_index('idx_warehouse_inventory_region', table_name='warehouse_inventory')
    op.drop_index('idx_warehouse_inventory_inventory_value', table_name='warehouse_inventory')
    op.drop_column('warehouse_inventory', 'inventory_value')
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_index('idx_scenario_warehouse', table_name='scenarios')
    op.drop_index('idx_scenario_status', table_name='scenarios')
    op.drop_index('idx_scenario_sku', table_name='scenarios')
    op.drop_index('idx_scenario_region', table_name='scenarios')
    op.drop_index('idx_scenario_last_run_status', table_name='scenarios')
    op.drop_index('idx_scenario_forecast_model', table_name='scenarios')
    op.drop_index('idx_scenario_created_by', table_name='scenarios')
    op.drop_index('idx_scenario_created_at', table_name='scenarios')
    op.drop_index('idx_scenario_category', table_name='scenarios')
    op.alter_column('scenarios', 'status',
               existing_type=sa.Enum('DRAFT', 'CREATED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scenariostatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('scenarios', 'exported_at')
    op.drop_column('scenarios', 'deleted_at')
    op.drop_column('scenarios', 'exported_by')
    op.drop_column('scenarios', 'deleted_by')
    op.drop_column('scenarios', 'executed_by')
    op.drop_column('scenarios', 'updated_by')
    op.drop_column('scenarios', 'created_by')
    op.drop_column('scenarios', 'forecast_model')
    op.drop_column('scenarios', 'progress')
    op.drop_column('scenarios', 'seasonal_impact')
    op.drop_column('scenarios', 'supply_delay')
    op.drop_column('scenarios', 'price_change')
    op.drop_column('scenarios', 'discount')
    op.drop_column('scenarios', 'demand_surge')
    op.drop_column('scenarios', 'sku')
    op.drop_column('scenarios', 'category')
    op.drop_column('scenarios', 'warehouse')
    op.drop_column('scenarios', 'region')
    op.drop_column('scenarios', 'time_horizon')
    op.drop_column('scenario_runs', 'estimated_completion')
    op.drop_column('scenario_runs', 'logs')
    op.drop_column('scenario_runs', 'total_steps')
    op.drop_column('scenario_runs', 'step_number')
    op.drop_column('scenario_results', 'summary_cards')
    op.drop_column('scenario_results', 'recommendation_ids')
    op.drop_column('scenario_results', 'all_skus')
    op.drop_column('scenario_results', 'inventory_difference')
    op.drop_column('scenario_results', 'inventory_simulation')
    op.drop_column('scenario_results', 'inventory_baseline')
    op.drop_column('scenario_results', 'inventory_labels')
    op.drop_column('scenario_results', 'forecast_difference')
    op.drop_column('scenario_results', 'forecast_simulation')
    op.drop_column('scenario_results', 'forecast_baseline')
    op.drop_column('scenario_results', 'forecast_labels')
    op.drop_column('scenario_comparisons', 'comparison_chart')
    op.add_column('recommendations', sa.Column('quantity', mysql.FLOAT(), nullable=False))
    op.add_column('recommendations', sa.Column('suggested_action', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index('idx_recommendation_warehouse', table_name='recommendations')
    op.drop_index('idx_recommendation_type', table_name='recommendations')
    op.drop_index('idx_recommendation_status', table_name='recommendations')
    op.drop_index('idx_recommendation_sku', table_name='recommendations')
    op.drop_index('idx_recommendation_priority', table_name='recommendations')
    op.drop_index('idx_recommendation_created_at', table_name='recommendations')
    op.drop_index('idx_recommendation_category', table_name='recommendations')
    op.alter_column('recommendations', 'status',
               existing_type=sa.Enum('PENDING', 'EXECUTED', 'IGNORED', 'IN_PROGRESS', name='recommendationstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('recommendations', 'priority',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='recommendationpriority'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('recommendations', 'recommendation_type',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'REORDER', 'PROCUREMENT', 'INVENTORY_OPTIMIZATION', 'WAREHOUSE_OPTIMIZATION', 'OVERSTOCK_MANAGEMENT', name='recommendationtype'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('recommendations', 'ignored_reason')
    op.drop_column('recommendations', 'ignored_at')
    op.drop_column('recommendations', 'ignored_by')
    op.drop_column('recommendations', 'executed_at')
    op.drop_column('recommendations', 'executed_by')
    op.drop_column('recommendations', 'key_details')
    op.drop_column('recommendations', 'discount_days')
    op.drop_column('recommendations', 'supplier_discount_available')
    op.drop_column('recommendations', 'supplier')
    op.drop_column('recommendations', 'predicted_demand')
    op.drop_column('recommendations', 'current_demand')
    op.drop_column('recommendations', 'forecast_value')
    op.drop_column('recommendations', 'region')
    op.drop_column('recommendations', 'warehouse')
    op.drop_column('recommendations', 'action_label')
    op.drop_column('recommendations', 'ai_confidence')
    op.drop_column('recommendations', 'expected_impact')
    op.drop_column('recommendations', 'estimated_savings')
    op.drop_column('recommendations', 'lead_time')
    op.drop_column('recommendations', 'recommended_quantity')
    op.drop_column('recommendations', 'current_stock')
    op.drop_column('recommendations', 'category')
    op.drop_column('recommendations', 'description')
    op.drop_column('recommendations', 'title')
    op.drop_constraint(None, 'inventory_transfers', type_='unique')
    op.drop_column('inventory_transfers', 'transfer_number')
    op.drop_column('inventory_transfers', 'tracking_number')
    op.drop_column('inventory_transfers', 'driver')
    op.drop_column('inventory_transfers', 'vehicle')
    op.drop_column('inventory_transfers', 'actual_arrival')
    op.drop_column('inventory_transfers', 'expected_arrival')
    op.drop_column('inventory_transfers', 'completed_by')
    op.drop_column('inventory_transfers', 'approved_by')
    op.drop_column('inventory_transfers', 'approval_status')
    op.drop_index(op.f('ix_inventory_movements_warehouse'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_sku'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index('idx_inventory_movements_warehouse', table_name='inventory_movements')
    op.drop_index('idx_inventory_movements_type', table_name='inventory_movements')
    op.drop_index('idx_inventory_movements_sku', table_name='inventory_movements')
    op.drop_index('idx_inventory_movements_created_at', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_history_warehouse'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_sku'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_id'), table_name='inventory_history')
    op.drop_index('idx_inventory_history_warehouse', table_name='inventory_history')
    op.drop_index('idx_inventory_history_sku', table_name='inventory_history')
    op.drop_index('idx_inventory_history_reason', table_name='inventory_history')
    op.drop_index('idx_inventory_history_created_at', table_name='inventory_history')
    op.drop_table('inventory_history')
    op.drop_index(op.f('ix_slow_moving_inventory_warehouse'), table_name='slow_moving_inventory')
    op.drop_index(op.f('ix_slow_moving_inventory_sku'), table_name='slow_moving_inventory')
    op.drop_index(op.f('ix_slow_moving_inventory_id'), table_name='slow_moving_inventory')
    op.drop_index('idx_slow_moving_warehouse', table_name='slow_moving_inventory')
    op.drop_index('idx_slow_moving_sku', table_name='slow_moving_inventory')
    op.drop_index('idx_slow_moving_level', table_name='slow_moving_inventory')
    op.drop_table('slow_moving_inventory')
    op.drop_index(op.f('ix_inventory_alerts_warehouse'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_sku'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_id'), table_name='inventory_alerts')
    op.drop_index('idx_inventory_alerts_warehouse', table_name='inventory_alerts')
    op.drop_index('idx_inventory_alerts_type', table_name='inventory_alerts')
    op.drop_index('idx_inventory_alerts_sku', table_name='inventory_alerts')
    op.drop_index('idx_inventory_alerts_severity', table_name='inventory_alerts')
    op.drop_index('idx_inventory_alerts_created_at', table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    # ### end Alembic commands ###
