"""recommendation updated

Revision ID: fe1de6f755eb
Revises: 9896f1b63766
Create Date: 2026-07-24 09:52:45.681116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe1de6f755eb'
down_revision: Union[str, Sequence[str], None] = '9896f1b63766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_stock_calculations_id'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_sku'), table_name='safety_stock_calculations')
    op.drop_index(op.f('ix_safety_stock_calculations_warehouse'), table_name='safety_stock_calculations')
    op.drop_table('safety_stock_calculations')
    op.drop_column('excess_stock', 'forecasted_demand_30days')
    op.drop_column('excess_stock', 'storage_risk_score')
    op.drop_column('excess_stock', 'total_carrying_cost')
    op.drop_column('excess_stock', 'estimated_liquidation_value')
    op.drop_column('excess_stock', 'region')
    op.drop_column('excess_stock', 'action_recommended')
    op.drop_column('excess_stock', 'potential_savings')
    op.drop_column('excess_stock', 'carrying_cost_per_unit_yearly')
    op.drop_index(op.f('idx_inventory_alerts_type'), table_name='inventory_alerts')
    op.drop_column('inventory_alerts', 'alert_type')
    op.drop_column('inventory_history', 'ip_address')
    op.drop_column('inventory_history', 'reference')
    op.drop_column('inventory_movements', 'reference_id')
    op.drop_index(op.f('transfer_number'), table_name='inventory_transfers')
    op.drop_column('inventory_transfers', 'completed_by')
    op.drop_column('inventory_transfers', 'transfer_number')
    op.drop_column('inventory_transfers', 'vehicle')
    op.drop_column('inventory_transfers', 'actual_arrival')
    op.drop_column('inventory_transfers', 'expected_arrival')
    op.drop_column('inventory_transfers', 'potential_cost_savings')
    op.drop_column('inventory_transfers', 'transfer_cost')
    op.drop_column('inventory_transfers', 'expected_days_in_transit')
    op.drop_column('inventory_transfers', 'approved_by')
    op.drop_column('inventory_transfers', 'reason')
    op.drop_column('inventory_transfers', 'approval_status')
    op.drop_column('inventory_transfers', 'driver')
    op.drop_column('inventory_transfers', 'recommended_transfer_date')
    op.drop_column('inventory_transfers', 'roi_percentage')
    op.drop_column('inventory_transfers', 'completed_at')
    op.drop_column('inventory_transfers', 'tracking_number')
    op.drop_column('reorder_points', 'economic_order_quantity')
    op.drop_column('scenario_results', 'all_skus')
    op.drop_column('scenario_results', 'forecast_difference')
    op.drop_column('scenario_results', 'inventory_difference')
    op.drop_column('scenario_results', 'forecast_json')
    op.drop_column('scenario_results', 'inventory_json')
    op.drop_column('scenario_results', 'summary_json')
    op.drop_column('scenario_runs', 'estimated_completion')
    op.drop_constraint(op.f('scenarios_ibfk_3'), 'scenarios', type_='foreignkey')
    op.drop_constraint(op.f('scenarios_ibfk_2'), 'scenarios', type_='foreignkey')
    op.drop_constraint(op.f('scenarios_ibfk_5'), 'scenarios', type_='foreignkey')
    op.drop_constraint(op.f('scenarios_ibfk_4'), 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'deleted_by')
    op.drop_column('scenarios', 'last_run_output')
    op.drop_column('scenarios', 'parameters')
    op.drop_column('scenarios', 'updated_by')
    op.drop_column('scenarios', 'exported_at')
    op.drop_column('scenarios', 'exported_by')
    op.drop_column('scenarios', 'deleted_at')
    op.drop_column('scenarios', 'executed_by')
    op.drop_column('slow_moving_inventory', 'last_sale_date')
    op.drop_column('slow_moving_inventory', 'action_recommended')
    op.drop_column('slow_moving_inventory', 'avg_daily_sales')
    op.drop_column('warehouse_inventory', 'economic_order_quantity')
    op.drop_column('warehouse_inventory', 'last_reorder_date')
    op.drop_column('warehouse_inventory', 'last_reorder_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_inventory', sa.Column('last_reorder_quantity', mysql.FLOAT(), nullable=True))
    op.add_column('warehouse_inventory', sa.Column('last_reorder_date', mysql.DATETIME(), nullable=True))
    op.add_column('warehouse_inventory', sa.Column('economic_order_quantity', mysql.FLOAT(), nullable=True))
    op.add_column('slow_moving_inventory', sa.Column('avg_daily_sales', mysql.FLOAT(), nullable=True))
    op.add_column('slow_moving_inventory', sa.Column('action_recommended', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('slow_moving_inventory', sa.Column('last_sale_date', mysql.DATETIME(), nullable=True))
    op.add_column('scenarios', sa.Column('executed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenarios', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('scenarios', sa.Column('exported_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenarios', sa.Column('exported_at', mysql.DATETIME(), nullable=True))
    op.add_column('scenarios', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenarios', sa.Column('parameters', mysql.JSON(), nullable=True))
    op.add_column('scenarios', sa.Column('last_run_output', mysql.JSON(), nullable=True))
    op.add_column('scenarios', sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('scenarios_ibfk_4'), 'scenarios', 'users', ['exported_by'], ['id'])
    op.create_foreign_key(op.f('scenarios_ibfk_5'), 'scenarios', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('scenarios_ibfk_2'), 'scenarios', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(op.f('scenarios_ibfk_3'), 'scenarios', 'users', ['executed_by'], ['id'])
    op.add_column('scenario_runs', sa.Column('estimated_completion', mysql.DATETIME(), nullable=True))
    op.add_column('scenario_results', sa.Column('summary_json', mysql.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_json', mysql.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_json', mysql.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('inventory_difference', mysql.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('forecast_difference', mysql.JSON(), nullable=True))
    op.add_column('scenario_results', sa.Column('all_skus', mysql.JSON(), nullable=True))
    op.add_column('reorder_points', sa.Column('economic_order_quantity', mysql.FLOAT(), nullable=False))
    op.add_column('inventory_transfers', sa.Column('tracking_number', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('roi_percentage', mysql.FLOAT(), nullable=False))
    op.add_column('inventory_transfers', sa.Column('recommended_transfer_date', mysql.DATETIME(), nullable=False))
    op.add_column('inventory_transfers', sa.Column('driver', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('approval_status', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('inventory_transfers', sa.Column('reason', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('inventory_transfers', sa.Column('approved_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('expected_days_in_transit', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_transfers', sa.Column('transfer_cost', mysql.FLOAT(), nullable=False))
    op.add_column('inventory_transfers', sa.Column('potential_cost_savings', mysql.FLOAT(), nullable=False))
    op.add_column('inventory_transfers', sa.Column('expected_arrival', mysql.DATETIME(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('actual_arrival', mysql.DATETIME(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('vehicle', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_transfers', sa.Column('transfer_number', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('inventory_transfers', sa.Column('completed_by', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('transfer_number'), 'inventory_transfers', ['transfer_number'], unique=True)
    op.add_column('inventory_movements', sa.Column('reference_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_history', sa.Column('reference', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('inventory_history', sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('inventory_alerts', sa.Column('alert_type', mysql.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('idx_inventory_alerts_type'), 'inventory_alerts', ['alert_type'], unique=False)
    op.add_column('excess_stock', sa.Column('carrying_cost_per_unit_yearly', mysql.FLOAT(), nullable=False))
    op.add_column('excess_stock', sa.Column('potential_savings', mysql.FLOAT(), nullable=False))
    op.add_column('excess_stock', sa.Column('action_recommended', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('excess_stock', sa.Column('region', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('excess_stock', sa.Column('estimated_liquidation_value', mysql.FLOAT(), nullable=False))
    op.add_column('excess_stock', sa.Column('total_carrying_cost', mysql.FLOAT(), nullable=False))
    op.add_column('excess_stock', sa.Column('storage_risk_score', mysql.FLOAT(), nullable=False))
    op.add_column('excess_stock', sa.Column('forecasted_demand_30days', mysql.FLOAT(), nullable=False))
    op.create_table('safety_stock_calculations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('warehouse', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('service_level', mysql.FLOAT(), nullable=False),
    sa.Column('z_score', mysql.FLOAT(), nullable=False),
    sa.Column('demand_std_dev', mysql.FLOAT(), nullable=False),
    sa.Column('lead_time_days', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_safety_stock', mysql.FLOAT(), nullable=False),
    sa.Column('current_safety_stock', mysql.FLOAT(), nullable=True),
    sa.Column('recommendation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_safety_stock_calculations_warehouse'), 'safety_stock_calculations', ['warehouse'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_sku'), 'safety_stock_calculations', ['sku'], unique=False)
    op.create_index(op.f('ix_safety_stock_calculations_id'), 'safety_stock_calculations', ['id'], unique=False)
    # ### end Alembic commands ###
