from datetime import datetime

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey

from sqlalchemy.orm import relationship

from fastapi_app.db.session import Base


class Upload(Base):
    __tablename__ = "uploads"

    id = Column(Integer, primary_key=True, index=True)

    # Original filename uploaded by the user
    filename = Column(String(255), nullable=False)

    # Unique filename generated by the system
    unique_filename = Column(String(255), nullable=False)

    # Physical file path
    file_path = Column(String(1024), nullable=False)

    # Public URL
    file_url = Column(String(1024), nullable=False)

    status = Column(String(50), default="pending", nullable=False)

    uploaded_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    user = relationship("User")

    uploaded_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return (
            f"<Upload(id={self.id}, "
            f"filename={self.filename}, "
            f"status={self.status})>"
        )